export const data = [
  {
    name: "Photo 1",
    url: "/images/lexus1.png",
    description: "LEXUS LX 570",
    date: "2020-01-01",
    type: "image/png",
  },
  {
    name: "Photo 2",
    url: "/images/lexus2.jpg",
    description: "LEXUS SUV",
    date: "2020-01-02",
    type: "image/jpg",
  },
  {
    name: "Photo 3",
    url: "/images/lexus3.png",
    description: "LEXUS LFA",
    date: "2020-01-03",
    type: "image/png",
  },
  {
    name: "Photo 4",
    url: "/images/lexus4.jpg",
    description: "LEXUS",
    date: "2020-01-04",
    type: "image/jpg",
  },
  {
    name: "Photo 5",
    url: "/images/lexus5.jpg",
    description: "LEXUS",
    date: "2020-01-05",
    type: "image/jpg",
  },
  {
    name: "Photo 6",
    url: "/images/lexus7.jpeg",
    description: "LEXUS JAOS",
    date: "2020-01-06",
    type: "image/jpeg",
  },
  {
    name: "Photo 7",
    url: "/images/lexus8.jpg",
    description: "LEXUS",
    date: "2020-01-07",
    type: "image/jpg",
  },
  {
    name: "Photo 8",
    url: "/images/lexus9.jpg",
    description: "LEXUS LF-GH",
    date: "2020-01-08",
    type: "image/jpg",
  },
  {
    name: "Photo 9",
    url: "/images/lexus10.jpg",
    description: "LEXUS SPORTS",
    date: "2020-01-09",
    type: "image/jpg",
  },
];
